name: meai_assistant_example
description: Example app for MeAI Assistant plugin
publish_to: 'none'

version: 1.0.3+4

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  meai_assistant:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: ReadexPro
      fonts:
        - asset: assets/fonts/readexpro/ReadexPro-Regular.ttf
          weight: 400
        - asset: assets/fonts/readexpro/ReadexPro-Bold.ttf
          weight: 700
        - asset: assets/fonts/readexpro/ReadexPro-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/readexpro/ReadexPro-Light.ttf
          weight: 300
        - asset: assets/fonts/readexpro/ReadexPro-Medium.ttf
          weight: 500
        - asset: assets/fonts/readexpro/ReadexPro-ExtraLight.ttf
          weight: 200